package com.drools.examples.mapreduce
 
import com.trexinhca.TrexinHCATest.Message;
 
rule "Hello World"
    when
        m : Message( status == Message.HELLO, myMessage : message )
    then
     //   System.out.println( myMessage );
        m.setMessage( "Goodbye cruel world" );
        m.setStatus( Message.GOODBYE );
        m.setDESYNPUF_ID("FOO");
        update( m );
end

rule "GoodBye"
    when
       m : Message( status == Message.GOODBYE, myMessage : message )
    then
      m.addClassification("FOO") ;
end


