package com.drools.examples.mapreduce
 
import com.trexinhca.MapperMessage;
 
rule "Hello World"
    when
        m : MapperMessage( status == MapperMessage.HELLO, myMessage : message )
    then
     //   System.out.println( myMessage );
        m.setMessage( "Goodbye cruel world" );
        m.setStatus( MapperMessage.GOODBYE );
        m.setDESYNPUF_ID("FOO");
        m.addClassification("BAR");
        update( m );
     
end

rule "GoodBye"
    when
       m : MapperMessage( status == MapperMessage.GOODBYE, myMessage : message )
    then
      m.addClassification("FOO") ;
end


