package com.drools.examples.mapreduce
 
import com.trexinhca.MapperMessage;
 
rule "Hello World"
    when
        m : MapperMessage( status == MapperMessage.HELLO, myMessage : message )
    then
     //   System.out.println( myMessage );
        m.setMessage( "Goodbye cruel world" );
        m.setStatus( MapperMessage.GOODBYE );
        m.setDESYNPUF_ID("XXX");
        m.addClassification("BAR");
        update( m );
  //   System.out.println("You made it here2");
end

rule "GoodBye"
    when
       m : MapperMessage( status == MapperMessage.GOODBYE, myMessage : message )
    then
      m.addClassification("FOO") ;
end

rule "Hospital Code 1"
    when
       m : MapperMessage(  HCPCS_CD_1 != "", myMessage : message )
    then
      m.addClassification(m.getHCPCS_CD_1()) ;
    // System.out.println("Here");
end
